"""The browser-based half of `tinker auth login`.

Orchestration only — each step lives elsewhere:

1. ask the Tinker API which WorkOS deployment it trusts (`auth_api`),
2. run the WorkOS device authorization grant (`device_auth`), opening a
   browser on the prefilled verification URL when one is available,
3. exchange the resulting WorkOS access token for a Tinker API key
   (`auth_api`), and
4. store that key as the default credential (`tinker.lib.credentials`), which
   is where both the SDK and the rest of the CLI pick it up.

The WorkOS access token is never written to disk: it only lives long enough
to mint the API key.
"""

from __future__ import annotations

import os
import socket
import sys
import threading
import webbrowser
from typing import Callable, Optional

import httpx

from tinker.lib import credentials

from .auth_api import TinkerAuthApi
from .device_auth import DeviceAuthClient
from .workos_api import DEFAULT_WORKOS_API_URL, WorkOsClient

# The note stored on every key this flow mints, so it is recognizable in the
# console's API key list.
API_KEY_NOTE = "Generated by Tinker CLI"
_HTTP_TIMEOUT_SECONDS = 30.0


def device_login(
    echo: Callable[[str], None],
    *,
    base_url: Optional[str] = None,
    workos_api_url: Optional[str] = None,
    credential_store: Optional[credentials.CredentialStore] = None,
    http_client: Optional[httpx.Client] = None,
    open_browser: Optional[Callable[[str], bool]] = None,
) -> credentials.GeneratedKey:
    """Log in through the browser and store the API key it mints.

    `echo` (usually click.echo) shows the user the confirmation code and
    verification URL while the flow waits on the browser.

    Blocks until the user approves the login or the device code expires.
    Raises DeviceAuthError or AuthApiError if any step fails.
    """
    owns_client = http_client is None
    client = http_client if http_client is not None else httpx.Client(timeout=_HTTP_TIMEOUT_SECONDS)
    key_name = api_key_name()
    try:
        api = TinkerAuthApi(client, base_url=base_url)
        workos = WorkOsClient(
            api.fetch_workos_client_id(),
            client,
            api_url=resolve_workos_api_url(workos_api_url),
        )
        device_auth = DeviceAuthClient(workos)
        authorization = device_auth.authorize()
        # Opening the prefilled URL saves the user typing the code, but both
        # are still shown: the browser may not open, and a browser on another
        # machine needs the code typed in anyway.
        opening = (open_browser or open_url)(authorization.verification_uri_complete)
        echo(f"Confirmation code: {authorization.user_code}")
        echo(f"Open this URL to log in: {authorization.verification_uri_complete}")
        if opening:
            echo("Opening it in your default browser -- open it yourself if nothing appears.")
        echo("Waiting for you to finish logging in...")

        access_token = device_auth.poll_for_access_token(authorization)
        created = api.create_api_key(access_token, name=key_name, note=API_KEY_NOTE)
    finally:
        if owns_client:
            client.close()

    if credential_store is None:
        credential_store = credentials.JsonCredentialStore(credentials.default_credentials_path())
    # The key is stored under the API key's own public id.
    key_id = str(created.id)
    record = credentials.GeneratedKey(key=created.api_key, name=key_name, details=created.details)
    credential_store.add_key(key_id, record)
    credential_store.set_default(key_id)
    return record


def api_key_name() -> str:
    """The name minted keys get: `tinker-cli-<machine name>`."""
    hostname = socket.gethostname().split(".", 1)[0].strip()
    return f"tinker-cli-{hostname or 'unknown'}"


def resolve_workos_api_url(api_url: Optional[str] = None) -> str:
    """The WorkOS API to authenticate against (overridable for non-prod)."""
    resolved = api_url or os.environ.get("TINKER_WORKOS_API_URL") or DEFAULT_WORKOS_API_URL
    return resolved.rstrip("/")


def open_url(url: str) -> bool:
    """Ask a browser to open `url`, reporting whether there was one to ask.

    The open runs on a daemon thread and its result is ignored: `webbrowser`
    runs a custom $BROWSER command in the foreground, which would otherwise
    block the login for as long as that browser stays open.
    """
    if not _browser_is_available():
        return False
    threading.Thread(target=_open_quietly, args=(url,), daemon=True).start()
    return True


def _open_quietly(url: str) -> None:
    """Open `url`, swallowing the failure of a browser that won't start."""
    try:
        webbrowser.open(url)
    except (webbrowser.Error, OSError):
        pass


def _browser_is_available() -> bool:
    """Whether launching a browser is worth attempting.

    On a headless Linux box or over SSH, `webbrowser` happily falls back to a
    console browser like lynx, which would take over the terminal the login is
    running in — so require a graphical session there.
    """
    if os.environ.get("BROWSER"):
        return True
    if sys.platform in ("darwin", "win32"):
        return True
    return bool(os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"))
