"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StopReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StopReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StopReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STOP_REASON_STOP: _StopReason.ValueType  # 0
    STOP_REASON_LENGTH: _StopReason.ValueType  # 1

class StopReason(_StopReason, metaclass=_StopReasonEnumTypeWrapper): ...

STOP_REASON_STOP: StopReason.ValueType  # 0
STOP_REASON_LENGTH: StopReason.ValueType  # 1
Global___StopReason: typing_extensions.TypeAlias = StopReason

@typing.final
class SampleResponse(google.protobuf.message.Message):
    """Public SampleResponse returned to SDK clients.
    Field numbers are compatible with tinker_internal.SampleResponse.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCES_FIELD_NUMBER: builtins.int
    PROMPT_LOGPROBS_FIELD_NUMBER: builtins.int
    TOPK_PROMPT_LOGPROBS_FIELD_NUMBER: builtins.int
    prompt_logprobs: builtins.bytes
    """np.array(prompt_logprobs, dtype=np.float32).tobytes()
    NaN for missing positions (e.g. first prompt token)
    """
    @property
    def sequences(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SampledSequence]: ...
    @property
    def topk_prompt_logprobs(self) -> Global___TopkPromptLogprobs:
        """Optional: absent means no topk was requested."""

    def __init__(
        self,
        *,
        sequences: collections.abc.Iterable[Global___SampledSequence] | None = ...,
        prompt_logprobs: builtins.bytes | None = ...,
        topk_prompt_logprobs: Global___TopkPromptLogprobs | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_prompt_logprobs", b"_prompt_logprobs", "_topk_prompt_logprobs", b"_topk_prompt_logprobs", "prompt_logprobs", b"prompt_logprobs", "topk_prompt_logprobs", b"topk_prompt_logprobs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_prompt_logprobs", b"_prompt_logprobs", "_topk_prompt_logprobs", b"_topk_prompt_logprobs", "prompt_logprobs", b"prompt_logprobs", "sequences", b"sequences", "topk_prompt_logprobs", b"topk_prompt_logprobs"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_prompt_logprobs", b"_prompt_logprobs"]) -> typing.Literal["prompt_logprobs"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_topk_prompt_logprobs", b"_topk_prompt_logprobs"]) -> typing.Literal["topk_prompt_logprobs"] | None: ...

Global___SampleResponse: typing_extensions.TypeAlias = SampleResponse

@typing.final
class SampledSequence(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_REASON_FIELD_NUMBER: builtins.int
    TOKENS_FIELD_NUMBER: builtins.int
    LOGPROBS_FIELD_NUMBER: builtins.int
    stop_reason: Global___StopReason.ValueType
    tokens: builtins.bytes
    """np.array(tokens, dtype=np.int32).tobytes()"""
    logprobs: builtins.bytes
    """np.array(logprobs, dtype=np.float32).tobytes()
    Optional, same length as tokens when present
    """
    def __init__(
        self,
        *,
        stop_reason: Global___StopReason.ValueType = ...,
        tokens: builtins.bytes = ...,
        logprobs: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_logprobs", b"_logprobs", "logprobs", b"logprobs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_logprobs", b"_logprobs", "logprobs", b"logprobs", "stop_reason", b"stop_reason", "tokens", b"tokens"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_logprobs", b"_logprobs"]) -> typing.Literal["logprobs"] | None: ...

Global___SampledSequence: typing_extensions.TypeAlias = SampledSequence

@typing.final
class TopkPromptLogprobs(google.protobuf.message.Message):
    """Dense N×K matrices for top-k prompt logprobs.
    Both token_ids and logprobs are row-major flattened: position i, rank j
    is at index i*k + j. Empty cells use token_id=0 and logprob=-99999.0.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_IDS_FIELD_NUMBER: builtins.int
    LOGPROBS_FIELD_NUMBER: builtins.int
    K_FIELD_NUMBER: builtins.int
    PROMPT_LENGTH_FIELD_NUMBER: builtins.int
    token_ids: builtins.bytes
    """Row-major N×K matrix of int32 token IDs"""
    logprobs: builtins.bytes
    """Row-major N×K matrix of float32 logprobs"""
    k: builtins.int
    """Number of top-k entries per position"""
    prompt_length: builtins.int
    """Number of prompt positions"""
    def __init__(
        self,
        *,
        token_ids: builtins.bytes = ...,
        logprobs: builtins.bytes = ...,
        k: builtins.int = ...,
        prompt_length: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["k", b"k", "logprobs", b"logprobs", "prompt_length", b"prompt_length", "token_ids", b"token_ids"]) -> None: ...

Global___TopkPromptLogprobs: typing_extensions.TypeAlias = TopkPromptLogprobs
