"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorCategory:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERROR_CATEGORY_UNSPECIFIED: _ErrorCategory.ValueType  # 0
    ERROR_CATEGORY_UNKNOWN: _ErrorCategory.ValueType  # 1
    ERROR_CATEGORY_SERVER: _ErrorCategory.ValueType  # 2
    ERROR_CATEGORY_USER: _ErrorCategory.ValueType  # 3

class ErrorCategory(_ErrorCategory, metaclass=_ErrorCategoryEnumTypeWrapper): ...

ERROR_CATEGORY_UNSPECIFIED: ErrorCategory.ValueType  # 0
ERROR_CATEGORY_UNKNOWN: ErrorCategory.ValueType  # 1
ERROR_CATEGORY_SERVER: ErrorCategory.ValueType  # 2
ERROR_CATEGORY_USER: ErrorCategory.ValueType  # 3
Global___ErrorCategory: typing_extensions.TypeAlias = ErrorCategory

class _QueueActivityState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _QueueActivityStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QueueActivityState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUEUE_ACTIVITY_STATE_UNSPECIFIED: _QueueActivityState.ValueType  # 0
    QUEUE_ACTIVITY_STATE_ACTIVE: _QueueActivityState.ValueType  # 1
    QUEUE_ACTIVITY_STATE_PAUSED_CAPACITY: _QueueActivityState.ValueType  # 2
    QUEUE_ACTIVITY_STATE_PAUSED_RATE_LIMIT: _QueueActivityState.ValueType  # 3

class QueueActivityState(_QueueActivityState, metaclass=_QueueActivityStateEnumTypeWrapper): ...

QUEUE_ACTIVITY_STATE_UNSPECIFIED: QueueActivityState.ValueType  # 0
QUEUE_ACTIVITY_STATE_ACTIVE: QueueActivityState.ValueType  # 1
QUEUE_ACTIVITY_STATE_PAUSED_CAPACITY: QueueActivityState.ValueType  # 2
QUEUE_ACTIVITY_STATE_PAUSED_RATE_LIMIT: QueueActivityState.ValueType  # 3
Global___QueueActivityState: typing_extensions.TypeAlias = QueueActivityState

@typing.final
class PollPromiseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["request_id", b"request_id"]) -> None: ...

Global___PollPromiseRequest: typing_extensions.TypeAlias = PollPromiseRequest

@typing.final
class PollPromiseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    TRY_AGAIN_FIELD_NUMBER: builtins.int
    FAILED_FIELD_NUMBER: builtins.int
    @property
    def payload(self) -> Global___SuccessPayload: ...
    @property
    def metadata(self) -> Global___MetadataOnly: ...
    @property
    def try_again(self) -> Global___TryAgain: ...
    @property
    def failed(self) -> Global___RequestFailed: ...
    def __init__(
        self,
        *,
        payload: Global___SuccessPayload | None = ...,
        metadata: Global___MetadataOnly | None = ...,
        try_again: Global___TryAgain | None = ...,
        failed: Global___RequestFailed | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["failed", b"failed", "metadata", b"metadata", "payload", b"payload", "result", b"result", "try_again", b"try_again"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["failed", b"failed", "metadata", b"metadata", "payload", b"payload", "result", b"result", "try_again", b"try_again"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["payload", "metadata", "try_again", "failed"] | None: ...

Global___PollPromiseResponse: typing_extensions.TypeAlias = PollPromiseResponse

@typing.final
class FetchPromisePayloadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["request_id", b"request_id"]) -> None: ...

Global___FetchPromisePayloadRequest: typing_extensions.TypeAlias = FetchPromisePayloadRequest

@typing.final
class FetchPromisePayloadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: builtins.int
    FAILED_FIELD_NUMBER: builtins.int
    @property
    def payload(self) -> Global___SuccessPayload: ...
    @property
    def failed(self) -> Global___RequestFailed: ...
    def __init__(
        self,
        *,
        payload: Global___SuccessPayload | None = ...,
        failed: Global___RequestFailed | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["failed", b"failed", "payload", b"payload", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["failed", b"failed", "payload", b"payload", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["payload", "failed"] | None: ...

Global___FetchPromisePayloadResponse: typing_extensions.TypeAlias = FetchPromisePayloadResponse

@typing.final
class SuccessPayload(google.protobuf.message.Message):
    """Terminal success: the request's response payload, returned verbatim as
    opaque bytes. `format` names the wire encoding of `data` (currently
    "json" or "proto").
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FORMAT_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    format: builtins.str
    data: builtins.bytes
    def __init__(
        self,
        *,
        format: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "format", b"format"]) -> None: ...

Global___SuccessPayload: typing_extensions.TypeAlias = SuccessPayload

@typing.final
class MetadataOnly(google.protobuf.message.Message):
    """Terminal success, payload-by-reference: the response is ready but its
    size exceeds the inline cap. The caller follows up with
    FetchPromisePayload to receive the bytes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_SIZE_FIELD_NUMBER: builtins.int
    payload_size: builtins.int
    def __init__(
        self,
        *,
        payload_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload_size", b"payload_size"]) -> None: ...

Global___MetadataOnly: typing_extensions.TypeAlias = MetadataOnly

@typing.final
class TryAgain(google.protobuf.message.Message):
    """Non-terminal: the request has not yet reached a terminal state. The
    caller should issue PollPromise again.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_STATE_FIELD_NUMBER: builtins.int
    QUEUE_STATE_REASON_FIELD_NUMBER: builtins.int
    queue_state: Global___QueueActivityState.ValueType
    queue_state_reason: builtins.str
    """Human-readable reason paired with queue_state (e.g. "capacity exceeded",
    "rate limit hit"). Empty when queue_state is ACTIVE or when no reason
    is available.
    """
    def __init__(
        self,
        *,
        queue_state: Global___QueueActivityState.ValueType = ...,
        queue_state_reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["queue_state", b"queue_state", "queue_state_reason", b"queue_state_reason"]) -> None: ...

Global___TryAgain: typing_extensions.TypeAlias = TryAgain

@typing.final
class RequestFailed(google.protobuf.message.Message):
    """Terminal failure of the underlying request. Retrieval itself succeeded;
    the caller should not retry retrieval. When `resubmit_originating_request`
    is true, the caller may re-issue the request that produced this
    `request_id` (a fresh `request_id` will be assigned).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    RESUBMIT_ORIGINATING_REQUEST_FIELD_NUMBER: builtins.int
    error: builtins.str
    category: Global___ErrorCategory.ValueType
    resubmit_originating_request: builtins.bool
    def __init__(
        self,
        *,
        error: builtins.str = ...,
        category: Global___ErrorCategory.ValueType = ...,
        resubmit_originating_request: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "error", b"error", "resubmit_originating_request", b"resubmit_originating_request"]) -> None: ...

Global___RequestFailed: typing_extensions.TypeAlias = RequestFailed
