# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tinker_api_pb2 as tinker__api__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tinker_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TinkerApiStub(object):
    """All methods may return the following gRPC status codes:
    UNAUTHENTICATED       failed auth.
    FAILED_PRECONDITION   failed billing check.
    INVALID_ARGUMENT      malformed request; caller (SDK) bug.
    RESOURCE_EXHAUSTED    rate limit hit; retry with backoff.
    INTERNAL              transient server error; retry immediately.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PollPromise = channel.unary_unary(
                '/tinker.api.v1.TinkerApi/PollPromise',
                request_serializer=tinker__api__pb2.PollPromiseRequest.SerializeToString,
                response_deserializer=tinker__api__pb2.PollPromiseResponse.FromString,
                _registered_method=True)
        self.FetchPromisePayload = channel.unary_unary(
                '/tinker.api.v1.TinkerApi/FetchPromisePayload',
                request_serializer=tinker__api__pb2.FetchPromisePayloadRequest.SerializeToString,
                response_deserializer=tinker__api__pb2.FetchPromisePayloadResponse.FromString,
                _registered_method=True)


class TinkerApiServicer(object):
    """All methods may return the following gRPC status codes:
    UNAUTHENTICATED       failed auth.
    FAILED_PRECONDITION   failed billing check.
    INVALID_ARGUMENT      malformed request; caller (SDK) bug.
    RESOURCE_EXHAUSTED    rate limit hit; retry with backoff.
    INTERNAL              transient server error; retry immediately.
    """

    def PollPromise(self, request, context):
        """Wait for the terminal status of a previously-submitted async request.
        May return SuccessPayload inline; otherwise returns MetadataOnly and
        the caller follows up with FetchPromisePayload to receive the bytes.
        If the request has not reached a terminal state within the call's
        deadline, returns an in-band TryAgain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchPromisePayload(self, request, context):
        """Fetch payload bytes for a request that PollPromise reported as
        ready. Bypasses the inline-size cap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TinkerApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PollPromise': grpc.unary_unary_rpc_method_handler(
                    servicer.PollPromise,
                    request_deserializer=tinker__api__pb2.PollPromiseRequest.FromString,
                    response_serializer=tinker__api__pb2.PollPromiseResponse.SerializeToString,
            ),
            'FetchPromisePayload': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchPromisePayload,
                    request_deserializer=tinker__api__pb2.FetchPromisePayloadRequest.FromString,
                    response_serializer=tinker__api__pb2.FetchPromisePayloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tinker.api.v1.TinkerApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tinker.api.v1.TinkerApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TinkerApi(object):
    """All methods may return the following gRPC status codes:
    UNAUTHENTICATED       failed auth.
    FAILED_PRECONDITION   failed billing check.
    INVALID_ARGUMENT      malformed request; caller (SDK) bug.
    RESOURCE_EXHAUSTED    rate limit hit; retry with backoff.
    INTERNAL              transient server error; retry immediately.
    """

    @staticmethod
    def PollPromise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinker.api.v1.TinkerApi/PollPromise',
            tinker__api__pb2.PollPromiseRequest.SerializeToString,
            tinker__api__pb2.PollPromiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchPromisePayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinker.api.v1.TinkerApi/FetchPromisePayload',
            tinker__api__pb2.FetchPromisePayloadRequest.SerializeToString,
            tinker__api__pb2.FetchPromisePayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
